name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "Running tests..." # Remplace avec des commandes pour tes vrais tests.

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t yassineharroume/ci-cd-docker-azure .
        docker push yassineharroume/ci-cd-docker-azure
  deploy-to-azure:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "ci-cd-docker-azure-app"  # Remplace par le nom de ton App Service
        slot-name: "staging"               # Si tu utilises un slot (sinon enlève cette ligne)
        images: "<ton_nom_utilisateur>/ci-cd-docker-azure:latest"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
